### ISSUE TITLE
次のcommitをしてください

### ISSUE THREAD

**Issue by kosuke-ikeura** [suke-chealsea/test#1]
git hub理解のためにcommitをもう一度してください

- [ ] git add

- [ ] git commit -m ""

- [ ] git push origin master

**Comment by suke-test** [comment]
かしこまりました。commitメッセージはどのようにすればよろしいでしょうか？

**Comment by kosuke-ikeura** [comment]
git commit -m "issue commit"としてください。

**Comment by suke-test** [comment]
👍
